packages:
  - apps/*
  - packages/*

catalog:
  '@trpc/client': ^11.5.0
  '@trpc/server': ^11.5.0
  better-auth: ^1.3.13
  dotenv: ^17.2.2
  drizzle-orm: 0.44.6
  next: 15.5.4
  tsdown: ^0.15.5
  zod: 4.1.12
